default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  user: 'postgres'
  password: 'postgres'
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production