test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
  public: true

google:
  service: GCS
  project: barbershop-rails
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'].as_json %>
  bucket: barbershop-rails
  public: true

google_dev:
  service: GCS
  project: barbershop-rails
  credentials: <%= Rails.root.join("config/secrets/barbershop-upload.json") %>
  bucket: barbershop-rails
  public: true
