test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
  public: true

google:
  service: GCS
  project: pet-finder-rails
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'].as_json %>
  bucket: pet-finder-rails

google_dev:
  service: GCS
  project: pet-finder-rails
  credentials: <%= Rails.root.join("config/secrets/pet-finder-upload.json") %>
  bucket: pet-finder-rails
